### ISSUE TITLE
undefined method `queue_adapter_name' for nil

### ISSUE THREAD

**Issue by zaychoer** [rails/solid_queue#196]
am I missing setup for recurring tasks ?

```
[SolidQueue] Starting Dispatcher(pid=59501, hostname=zaychos-MacBook-Air.local, metadata={:polling_interval=>1, :batch_size=>500, :concurrency_maintenance_interval=>600, :recurring_schedule=>nil})
[SolidQueue] Starting Dispatcher(pid=59502, hostname=zaychos-MacBook-Air.local, metadata={:polling_interval=>1, :batch_size=>500, :concurrency_maintenance_interval=>600, :recurring_schedule=>{ :settlement_process=>{:schedule=>"42 10 * * *", :class_name=>"SettlementHandlerJob", :arguments=>[]}, :disbursement_process=>{:schedule=>"43 10 * * *", :class_name=>"DisbursementHandlerJob", :arguments=>[]}}})
[SolidQueue] Starting Worker(pid=59503, hostname=zaychos-MacBook-Air.local, metadata={:polling_interval=>0.1, :queues=>"*", :thread_pool_size=>5})

[SolidQueue] undefined method `queue_adapter_name' for nil
[SolidQueue] undefined method `queue_adapter_name' for nil
[SolidQueue] undefined method `queue_adapter_name' for nil
```

i have already added solid_queue to the application configuration and followed the documentation.
other tasks are running well, except for the recurring task.

``
 config.active_job.queue_adapter = :solid_queue
 ``

here is solid_queue.yml

```
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
    - recurring_tasks:
        settlement_process:
          class: "SettlementHandlerJob"
          schedule: "42 10 * * *" 
        disbursement_process:
          class: "DisbursementHandlerJob"
          schedule: "43 10 * * *" 
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

sandbox:
 <<: *default

test:
 <<: *default

production:
 <<: *default


```

**Comment by rosa** [comment]
Hey @zaychoer thanks for reporting this! This looks like an scenario I'm not handling gracefully 😅 Is it possible one/some of your recurring task classes doesn't exist in your app? From these: 
```
class: "SettlementHandlerJob"
class: "DisbursementHandlerJob"
```
Can you open a Rails console and see if they're defined?

**Comment by zaychoer** [comment]
> Hey @zaychoer thanks for reporting this! This looks like an scenario I'm not handling gracefully 😅 Is it possible one/some of your recurring task classes doesn't exist in your app? From these:
> 
> ```
> class: "SettlementHandlerJob"
> class: "DisbursementHandlerJob"
> ```
> 
> Can you open a Rails console and see if they're defined?

Hey, @rosa , that was my mistake. After checking, I realized that the task class was inside a directory. After adding the directory name before the task class, it ran well. Here is the fixed configuration:

```
dispatchers:
    - polling_interval: 1
      batch_size: 500
    - recurring_tasks:
        settlement_process:
          class: "Bank::SettlementHandlerJob"
          schedule: "42 10 * * *" 
        disbursement_process:
          class: "Bank::DisbursementHandlerJob"
          schedule: "43 10 * * *" 
```
