### ISSUE TITLE
Database connection error in Solid Queue, but not Rails app

### ISSUE THREAD

**Issue by floydj** [rails/solid_queue#215]
My syslog keeps filling up with errors like:

```
ActiveRecord::DatabaseConnectionError: There is an issue connecting with your hostname: <<DB SERVER IP>>. (ActiveRecord::DatabaseConnectionError)
Please check your database configuration and ensure there is a valid connection to your database.
...stack trace removed...
PG::ConnectionBad: connection to server at "<<DB SERVER IP>>", port 5432 failed: fe_sendauth: no password supplied (PG::ConnectionBad)
```

I'm assuming Solid Queue is using the `config/database.yml` from my Rails app to connect to Postgres:

```yaml
production:
  <<: *default
  database: purchasing_production
  host: <<DB SERVER IP>>
  port: 5432
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
```

The Rails app is able to connect fine. I have checked that the POSTGRES_PASSWORD environment variable is set. I've also verified there's only one Solid Queue process running.

Oddly enough, when I send email with the `deliver_later` method, the emails are properly sent. So it seems that Solid Queue is processing something, but not able to connect to the database? What am I missing here?
