### ISSUE TITLE
Database pool size in multi workers setup

### ISSUE THREAD

**Issue by pasl** [rails/solid_queue#255]
Hi

I am trying to understand how the database connection pool work in a multi-workers configuration.

Let's say I have

database.yml
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
```

solid_queue.yml
```yml
default: &default
  dispatchers:
    - polling_interval: 1 # default 1
      batch_size: 500
      concurrency_maintenance_interval: 600 # wait in second for concurrency to be maintained (default 600)
    workers:
    - queues: [ real_time, default, background ]
      threads: 5
      processes: 1
      polling_interval: 0.1 # default 0.1
    - queues: [ batch_searches ]
      threads: 50
      processes: 1
      polling_interval: 0.1 # default 0.1
```

In the batch_searches queue I want to be able to execute 50 jobs in parallel and each job should have a database connection.

Is it the job of SolidQueue to handle the database connection pool ?

If it use the same database.yml configuration to generate a new active_record connection_pool I assume there will be 1 pool per SolidQueue Process shared among all threads ?

So If I need a pool size of 50 how can I archive this without modifying the PUMA worker pool size.

Thank you

**Comment by rosa** [comment]
Hey @pasl, sorry for the delay! I had somehow missed the notification for this issue 😳 

With that configuration, you'll need a database pool size of at least 52, 50 for each thread + 1 for the worker itself + 1 for its heartbeat task. 

> So If I need a pool size of 50 how can I archive this without modifying the PUMA worker pool size.

I think you can just do this: 
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 52
  timeout: 5000
``` 
and that won't affect Puma's worker pool size in any way.
