### ISSUE TITLE
Not Finding Recurring Jobs

### ISSUE THREAD

**Issue by imack** [rails/solid_queue#257]
Hoping for some help. I'm trying to run a job every minute, but the job isn't enqueued and I don't see it in the dashboard under recurring jobs. This is the `config/solid_queue.yml`:

```
default: &default
  dispatchers:
    - polling_interval: 1
      recurring_tasks:
        open_update_job:
          class: OpenUpdateJob
          schedule: every minute
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```
I'm on `0.3.3` and the 'solid_queue_recurring_executions' table has been created. This is in development mode.

If I manually run `OpenUpdateJob.perform_later` it runs fine.
