### ISSUE TITLE
On 0.4 Errno::ECHILD errors are popping up

### ISSUE THREAD

**Issue by npezza93** [rails/solid_queue#274]
Recently upgraded to 0.4 and im seeing a bunch of Errno::ECHILD errors now. solid_queue seems to be running fine but sentry is still reporting the error. 
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/b1b95d60-a5ab-4b97-85df-5fcfbcf25e55">

Running solid_queue with: bin/rails solid_queue:start

config:
```
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
         [..]
  workers:
    - queues: "*"
      threads: 1
      processes: 5
      polling_interval: 0.75
    - queues: [default,searchkick,ahoy,mailers,events,push]
      threads: 1
      processes: 1
      polling_interval: 0.75

```

**Comment by npezza93** [comment]
Nevermind. This is a me thing....Whoops

**Comment by willnet** [comment]
@npezza93 We are also investigating the cause of a similar error. Could you please share how you resolved it for our reference?

**Comment by MikeMcQuaid** [comment]
@willnet The issue we saw was from https://github.com/rails/solid_queue/commit/057977b8b32db6666fd45262c7b6b666bc0a3e1c. If you have any configuration defined (we had some `recurring_tasks`) then the `workers` will no longer be defined. Our fix was adding these options explicitly to our `config/solid_queue.yml`: https://github.com/rails/solid_queue/blob/addd8701c342062deabcd3bf0f937fc031bf2d5b/lib/solid_queue/configuration.rb#L5-L10

**Comment by npezza93** [comment]
In our qa environment (RAILS_ENV=qa) we were experiencing it because in our solid_queue.yml we were missing a key for qa. So im guessing it was running in the new async mode. I  added a dispatcher and worker for the qa key and everything was hunky dory.

**Comment by rosa** [comment]
Oh, @npezza93, in that case it would have run in the regular (`fork`) mode, but with the default configuration 🤔 Right now to start solid queue in the new async mode you need to use the Puma plugin.

**Comment by npezza93** [comment]
Ohh my mistake. Yea we were running it in its own process with solid_queue:start. Weird. I can give you a stack trace if thats helpful at all?

**Comment by MikeMcQuaid** [comment]
@rosa if it's helpful: in my case the issue was we previously declared config for just the `dispatchers` but left `workers` implicit and the change in https://github.com/rails/solid_queue/commit/057977b8b32db6666fd45262c7b6b666bc0a3e1c meant that this meant no workers were started any more.

**Comment by kaka-ruto** [comment]
Same for me as well, I had forgotten to define this
<img width="209" alt="Screenshot 2024-08-09 at 21 11 27" src="https://github.com/user-attachments/assets/93ebd349-64f6-4415-a8ce-584ec3a78ad8">

**Comment by lesliepoolman** [comment]
I had the same issue in my Dev environment where I only had the production settings attached:
```
# default: &default

# development:
#  <<: *default

# test:
#  <<: *default

production:
  # <<: *default
  dispatchers:
    - recurring_tasks:
        my_periodic_job:
          class: JobName
          schedule: every day
```
What worked for me is adding the defaults like so:

```
default: &default
  dispatchers:
    - concurrency_maintenance_interval: 300
      polling_interval: 1
      batch_size: 500

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  dispatchers:
    - recurring_tasks:
        my_periodic_job:
          class: JobName
          schedule: every day
```

Hope this is useful to someone :)
