### ISSUE TITLE
Solid Queue no longer starts with rails/server in the production env

### ISSUE THREAD

**Issue by kirillshevch** [rails/solid_queue#281]
Hi folks!

After the version bump from 0.3 to 0.5, Solid Queue no longer starts while starting Rails process in the production environment. Is this expected behavior and should it now be treated exclusively as a separate run via `bundle exec rake solid_queue:start`? It was quite handy to run it all together for small projects.

I didn't find anything regarding that in UPGRADING.md

Thanks!

**Comment by rosa** [comment]
Hey @kirillshevch, that's odd! Were you using the Puma plugin before? That was the only way for Solid Queue to start automatically. That hasn't changed. What configuration do you have?

**Comment by kirillshevch** [comment]
Hi @rosa,
Yes, I was using `plugin :solid_queue` in puma config, no changes there. Rails starts in Docker container `CMD ["./bin/rails", "server"]`

**Comment by rosa** [comment]
Thanks @kirillshevch! What's your Solid Queue configuration?

**Comment by gugatxr** [comment]
Hi, I have the same problem. 


puma version: 6.4.2
rails version: 7.1.3.4
solid_queue: 0.6.0
ruby: 3.3.0

Using `plugin :solid_queue`

My config: 

```
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
```
