### ISSUE TITLE
Recurring tasks not being scheduled (no unique index found)

### ISSUE THREAD

**Issue by tsvallender** [rails/solid_queue#292]
At some point my recurring tasks have stop being scheduled. I presume one of the upgrades has caused this but I’m unsure which—I didn’t immediately notice the tasks weren’t running.

This is my configuration:
```yaml
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
      recurring_tasks:
        generate_journeys:
          class: GenerateJourneysJob
          schedule: every minute
        update_boat_designs:
          class: UpdateBoatDesignsJob
          schedule: every 15 minutes
        update_no_foreign_land:
          class: UpdateNoForeignLandJob
          schedule: every 15 minutes
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

production:
 <<: *default
```

I’m deploying with Kamal and run Solid Queue in its own container with `bundle exec rake solid_queue:start`.

I can see the jobs listed in mission_control-jobs:

![image](https://github.com/user-attachments/assets/c618886e-5bec-4cc4-9770-61c3e4e7cb9d)

But as you can see they’re no longer being enqueued. I also can’t see any errors being raised.
