### ISSUE TITLE
Question: How do I start specific workers only?

### ISSUE THREAD

**Issue by harry-herskowitz** [rails/solid_queue#295]
I am trying to split queues into different workers that I can turn on and off easily, something like this:

Procfile:
```
worker_couchbase: QUEUE=couchbase bundle exec rake solid_queue:start
worker_scheduler: QUEUE=scheduler bundle exec rake solid_queue:start
```

Config File:
 ```
 workers:
    - queues: 'couchbase'
      threads: 3
      processes: 1
      polling_interval: 0.1
    - queues: 'scheduler'
      threads: 3
      processes: 1
      polling_interval: 0.1
```
What's the proper syntax for starting just one specific worker?

**Comment by rosa** [comment]
Hey @harry-herskowitz! With the current configuration, just running `solid_queue:start, the workers will start each one in its own process, so you can terminate them individually. 

If you want to have two different supervisors, each one supervising a single worker, then you'd need to have two config files, one for each worker, and set the config file via `SOLID_QUEUE_CONFIG`. I'm planning to build a proper CLI and add this as an option but in the meantime that'd be the way. Something like: 
```
SOLID_QUEUE_CONFIG=config/solid_queue/couchbase.yml bundle exec rake solid_queue:start
```
And then `config/solid_queue/couchbase.yml` would look like: 
```yml
workers:
   - queues: 'couchbase'
     threads: 3
     processes: 1
     polling_interval: 0.1
```
