### ISSUE TITLE
Running `rails db:migrate` clears out `queue_schema.rb`.

### ISSUE THREAD

**Issue by gregschmit** [rails/solid_queue#329]
I am trying to install latest solid queue into a project I'm working on, but when I run `rails db:migrate` then it clears out the `queue_schema.rb` file. I can load the schema with `rails db:prepare`, however I do have to run migrations in my primary database, but it always clears out the queue schema. Is there a migration file or multiple migration files for solid queue anymore?

**Comment by gregschmit** [comment]
I guess I should just take the schema and dump it into a migration file. Sorry if this is a noobie question but I haven't used multiple DBs in Rails before so I'm trying to figure out if my configuration is broken or if this is expected behavior.

**Comment by gregschmit** [comment]
Maybe if this is the normal current behavior solid queue install should put a migration into the `solid_queue_migrate` path? Because it does say to set the database configuration `migrations_paths` to `queue_migrate`, so I think that would indicate something should be there.

**Comment by rosa** [comment]
Huh, sorry for the trouble, @gregschmit! That seems really strange! It should just work without you having to do anything, and it shouldn't clear the queue schema. Would you mind sharing your `database.yml` configuration?

**Comment by gregschmit** [comment]
Sure, here is my database.yml:

```
default: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
  timeout: 5000

development:
  primary:
    <<: *sqlite
    database: db/development.sqlite3
  solid_queue:
    <<: *sqlite
    database: db/development_queue.sqlite3
    migrations_paths: db/solid_queue_migrate

test:
  primary:
    <<: *sqlite
    database: db/test.sqlite3
  solid_queue:
    <<: *sqlite
    database: db/test_queue.sqlite3
    migrations_paths: db/solid_queue_migrate

production:
  primary:
    <<: *sqlite
    database: db/production.sqlite3
  solid_queue:
    <<: *sqlite
    database: db/production_queue.sqlite3
    migrations_paths: db/solid_queue_migrate
```

In hindsight to me it makes perfect sense that the schema would be cleared, because there are no migration files inside `db/solid_queue_migrate`. By the way, I originally had everything set to `queue_migrate` and `queue_schema.rb` because that was the default but ended up prepending `solid_` just for consistency. I was able to make everything work by putting the template `queue_schema.rb` into a migration file inside `the `db/queue_migrate` directory and now things are smooth.

**Comment by gregschmit** [comment]
I guess my main question is why solid queue doesn't install migrations even in a separate directory, and why the `bin/rails solid_queue:install:migrations` was removed (and not replaced by `rails railties:install:migrations FROM=solid_queue`). It seems as long as there are no migrations, then anytime someone runs `migrate` the schema would be cleared if they don't have an existing local database. The user would have to remember to load the schema first for that particular database.

**Comment by eduardinni** [comment]
> Huh, sorry for the trouble, @gregschmit! That seems really strange! It should just work without you having to do anything, and it shouldn't clear the queue schema. Would you mind sharing your `database.yml` configuration?

For me it didn't work automatically because I'm using `config.active_record.schema_format = :sql`.

I've converted the template schema into a migration and now it works, but I'm worried about future changes on the schema, I'll keep the generated `queue_schema.rb` and check the diffs. Are the future updates planned to land as a migration in the queue's `migrations_paths`?

thanks for the work on this amazing gem 💎

**Comment by rosa** [comment]
Yes, these are great points @gregschmit and @eduardinni. We had planned to include future changes to the schema as regular migrations in the queue db migration paths, yes, but you both bring up a good point... let me think a bit more about this. 

Thank you 🙏

**Comment by scratchoo** [comment]
the `bin/rails solid_queue:install` command created a queue_schema.rb file but with `rails db:prepare `the database was never created

what I did is:

- I created a task file:  `lib/tasks/solid_queue.rake`
- then I run that task `rails solid_queue:load_schema`

This created the database from the solid queue schema file

Finally don't forget to add `config.active_job.queue_adapter = :solid_queue` to your environment file or to application.rb if you are using solid queue in all environments

I might not be that sophisticated, but it was confusing for me that the install generator was creating a schema file instead of migration file (probably better under a "queue_migrate" folder) and it was not loaded into the database without that rake task!

**Comment by rosa** [comment]
> the bin/rails solid_queue:install command created a queue_schema.rb file but with rails db:prepare the database was never created

Is it possible you didn't have the right configuration in `database.yml` before running `db:prepare`? 🤔

**Comment by dhh** [comment]
@scratchoo I just replicated your account by creating a new app, running solid_queue:install, and the running db:prepare. It doesn't create the database because it hasn't been configured in config/database.yml. Once I added the configuration there (see the top section under # Installation), then it created the database as expected on db:migrate.

@gregschmit You've found a multi-db handling bug in Rails. I've opened https://github.com/rails/rails/issues/52829 to track it. Thanks for tickling that! We fixed a related issue in db:migrate, but db:migrate must be taking a different path. We'll get it sorted before Rails 8.0.0.final. Maybe we can even backport the fix to 7.2.x.

**Comment by scratchoo** [comment]
@dhh still not working for me,

I have this on database.yml

```
development:
  primary:
    <<: *default
    database: demo_dev
  queue:
    <<: *default
    database: demo_production_queue
    migrations_paths: db/queue_migrate
```

When I run `rails db:prepare` the output is:

Created database 'demo_dev'
Created database 'demo_production_queue'
Created database 'demo_test'

My own migrations seem to run without terminal output (when using db:prepare) but there is no migrations files related to solid_queue that was created, even if I create the folder `db/queue_migrate` myself, there is no chance!

Supposing that the solid_queues migration files shouldn't be created and only `queue_schema.rb` should be enough, still the solid_queue tables are never created from that!

My Rails version is 7.1.3.4 in case I am missing something
