### ISSUE TITLE
No connection pool for 'SolidQueue::Record' found

### ISSUE THREAD

**Issue by gczh** [rails/solid_queue#331]
I'm trying to setup solid_queue for rails 7.2.1 and

I'm getting the error in terminal when i run `bundle exec rails solid_queue:start`

```bash
ActiveRecord::ConnectionNotEstablished: No connection pool for 'SolidQueue::Record' found. (ActiveRecord::ConnectionNotEstablished)
```

In my `database.yml`

```yml
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: test_app_development
  queue:
    <<: *default
    database: test_app_development_queue
    migrations_paths: db/queue_migrate
```

Running `rails s` works and it's clearly connecting to the primary database.

In my `application.rb`, I have the following:

```ruby
# Database
config.active_record.writing_role = :primary
config.active_record.reading_role = :primary
```

**Note:** I have that setup as I have other databases configured in my database.yml and wanted to be explicit that all the app data goes to primary.

After commenting it out, I can verify that the queue is able to connect to the database now. However, I'm wondering if this is the expected behaviour as we should be able to specify those configuration in `application.rb` and it shouldn't affect how `solid_queue` connects to the database?
