### ISSUE TITLE
Best way to play around with Solid Queue in development?

### ISSUE THREAD

**Issue by jeromedalbert** [rails/solid_queue#332]
Solid Queue used to use migrations on a single database, which was nice if you wanted to have everything in the same database in development.

Now Solid Queue uses schemas, which is nice since it does not clutter a brand new Rails 8 app with migrations. The schemas are for separate databases, which makes sense for production (it would be nice to document why by the way, like I guess better isolation or performance). I understand that the library is more intended for production as [explained](https://github.com/rails/solid_queue/issues/329#issuecomment-2336436083) by Rosa:

> Solid Queue is more intended for production, Rails ships with another adapter for development, the async adapter.

But it would be nice to be able to easily play around with it in on your local environment, to kick the tires, reproduce production issues in your local, get a feel for how it works with [mission_control-jobs](https://github.com/rails/mission_control-jobs), and see if any configuration changes you're making to your Solid Queue setup works correctly on your local before deploying them to minimize issues.

If Solid Queue in development is not a default (which would be nice), then I think it should be easy to set it up on one's local. So far I can think of 3 ways:

1. Keep Solid Queue in a separate schema in production, but one schema in development. I don't know if that's possible. But having everything in one schema keeps the development setup simple, since having multiple databases looks more like a production concern. That would be the simplest setup short of using the async adapter. However it would be harder to remove solid queue (short of using `--skip-solid`) since I guess you would have to manually edit the schema.
2. Provide an example `database.yml` setup in some way, like in docs or as comments in that file. This is how I set it up on my local for a new app using postgres:

    ```yml
    default: &default
      adapter: postgresql
      encoding: unicode
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

    cache: &cache
      <<: *default
      migrations_paths: db/cache_migrate
    queue: &queue
      <<: *default
      migrations_paths: db/queue_migrate

    development:
      primary:
        <<: *default
        database: myapp_development
      cache:
        <<: *cache
        database: myapp_development_cache
      queue:
        <<: *queue
        database: myapp_development_queue

    test:
      <<: *default
      database: myapp_test

    production:
      primary:
        <<: *default
        url: <%= ENV['DATABASE_URL'] %>
      cache:
        <<: *cache
        url: <%= ENV['DATABASE_URL']&.+('_cache') %>
      queue:
        <<: *queue
        url: <%= ENV['DATABASE_URL']&.+('_queue') %>
    ```

    That works fine although I feel like it is a bit cluttered for a new app. Maybe I could simplify this but I am unsure how. I guess I could dynamically set the database names like `database: "myapp_#{Rails.env}_queue"`) and hoist those definitions in `&queue` etc.
3. Provide a command like `bin/rails solid_queue:install:dev` that sets up everything for your development environment (with a `database.yml` similar to point 2).

What do people think is the best way to play around with Solid Queue in development?

(I realize this question applies to Solid Cache too since it also uses a separate schema, so it may be more of a general Rails question. I can repost on the Rails core forum or the Rails github discussions if needed)

**Comment by rosa** [comment]
Hey @jeromedalbert, good question! I think the best way to play around with Solid Queue (and Solid Cache) in development is to keep the databases separate as well. 

I think your idea of an install command for dev or a commented out example is good, that'll help people for sure.

**Comment by jeromedalbert** [comment]
Related: https://github.com/rails/solid_queue/pull/334 and https://github.com/rails/solid_cable/pull/37 added instructions to use a single database. Although with those solutions you would have a single database for both development and production.

**Comment by jeromedalbert** [comment]
Just some updates on how I currently set up my `database.yml` if that can help or inspire anyone.

- For SQLite:

    ```yaml
    default: &default
      adapter: sqlite3
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
      timeout: 5000

    databases: &databases
      primary:
        <<: *default
        database: storage/<%= Rails.env %>.sqlite3
      cache:
        <<: *default
        database: storage/<%= Rails.env %>_cache.sqlite3
        migrations_paths: db/cache_migrate
      queue:
        <<: *default
        database: storage/<%= Rails.env %>_queue.sqlite3
        migrations_paths: db/queue_migrate
      cable:
        <<: *default
        database: storage/<%= Rails.env %>_cable.sqlite3
        migrations_paths: db/cable_migrate

    development:
      <<: *databases

    test:
      <<: *default
      database: storage/test.sqlite3

    production:
      <<: *databases
    ```


- For database servers like like Postgres or MySQL (I use dotenv in development so it allows me to use the same setup in dev and prod):

    ```yaml
    default: &default
      adapter: postgresql
      encoding: unicode
      pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

    databases: &databases
      primary:
        <<: *default
        url: <%= ENV['DATABASE_URL'] %>
      cache:
        <<: *default
        url: <%= URI.parse(ENV['DATABASE_URL']).tap { |u| u.path += '_cache' } if ENV['DATABASE_URL'] %>
        migrations_paths: db/cache_migrate
      queue:
        <<: *default
        url: <%= URI.parse(ENV['DATABASE_URL']).tap { |u| u.path += '_queue' } if ENV['DATABASE_URL'] %>
        migrations_paths: db/queue_migrate
      cable:
        <<: *default
        url: <%= URI.parse(ENV['DATABASE_URL']).tap { |u| u.path += '_cable' } if ENV['DATABASE_URL'] %>
        migrations_paths: db/cable_migrate

    development:
      <<: *databases

    test:
      <<: *default
      database: myapp3_test

    production:
      <<: *databases
    ```

I like how in both cases I am able to reuse the same config in development and prod, so it makes for a shorter and simpler `database.yml`.
