### ISSUE TITLE
The `queue` database is not configured for the `production` environment.

### ISSUE THREAD

**Issue by DickyMacias** [rails/solid_queue#342]
Hi, @rosa. Here again asking something that maybe is not an issue 😅

I upgraded SolidQueue from 0.3 to 0.9, I followed the upgrading readme and jump first to 0.6, and then to 0.8.x and now to 0.9. Everything went fine and I could use the queue. Then when I deployed to production, I found out the following error.

```
/usr/local/bundle/ruby/3.1.0/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:229:in `resolve_symbol_connection': 
The `queue` database is not configured for the `production` environment. (ActiveRecord::AdapterNotSpecified)

Available database configurations are:

default
development
test
production
```

I am using Docker and its working in development environment, but production.

Hope you can help me to find out what the issue can be.

Here are my database settings:
```
default: &default
  adapter: postgresql
  encoding: unicode
  host: host.docker.internal
  username: <%= ENV['DEV_DATABASE_USERNAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE_NAME'] %>
  port: 5432

test:
  primary:
    <<: *default
    database: <%= ENV['TEST_DATABASE_NAME'] %>
    username: <%= ENV['TEST_DATABASE_USERNAME'] %>
    password: <%= ENV['TEST_DATABASE_PASSWORD'] %>
    port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
```

And the queue.yml config
```
default: &default
  dispatchers:
    - polling_interval: <%= ENV['POLLING_INTERVAL'] || 15 %>
      batch_size: 10
      concurrency_maintenance_interval: 3600
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: <%= ENV['POLLING_INTERVAL'] || 15 %>

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
```

Also I have the following config in production.rb in the environments folder
```
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = {database: {writing: :queue}}
```

Thanks in advance for your check out.

**Comment by DickyMacias** [comment]
I already found out how to solve it. I added the queue database in the YAML config.

```
production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
```

I am not completely sure is the best way, but it works.

**Comment by DickyMacias** [comment]
I already found out how to solve it. I added the queue database in the YAML config.

```
production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
```

I am not completely sure is the best way, but it works.

**Comment by douglara** [comment]
I’m using SQLite and I was able to fix it updating my `database.yml` to:

```

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  queue:
    <<: *default
    database: storage/test_queue.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
```
