### ISSUE TITLE
Rake Task Support in Recurring Jobs

### ISSUE THREAD

**Issue by kaka-ruto** [rails/solid_queue#379]
Would you be open to supporting rake tasks in recurring jobs?

Something like this

```yaml
production:
  generate_sitemap:
    rake: sitemap:refresh
    flags:
      s: true
      verbose: true
    schedule: every day at 3am

  custom_rake_task:
    rake: my:custom:task
    args: ['arg1', 'arg2']
    flags:
      trace: true
    schedule: every hour
```

I can give it a jab.

**Comment by kylekeesling** [comment]
I like this idea. To solve this for now I created a generic Job that allows me to pass rake tasks in as the argument:

```ruby
# frozen_string_literal: true

class RakeTaskJob < ApplicationJob
  queue_as :default

  def perform(command)
    require "rake"

    Rake.application.init
    Rake.application.load_rakefile

    Rake::Task[command].invoke
  end
end
```

Then I can just do this in `recurring.yml`:

```yaml
  monday_job:
    class: RakeTaskJob
    args: "scheduled_tasks:monday_jobs"
    schedule: every Monday at 7am UTC
```

**Comment by gazeldx** [comment]
```ruby
# works in Rails 8
class RakeTaskJob < ApplicationJob
  queue_as :default

  def perform(task_name)
    YourAppName::Application.load_tasks

    Rake::Task[task_name].invoke
  end
end
```

```yml
development:
  refresh_sitemap_job:
    class: RakeTaskJob
    args: "sitemap:refresh:no_ping"
    schedule: every minute
```
