### ISSUE TITLE
`queue_schema.rb` dissapears after `rails db:migrate:reset`

### ISSUE THREAD

**Issue by konradperlowski** [rails/solid_queue#384]
Hi, I added solid queue configuration for my development environment and after running `rails db:migrate:reset` command (or manually running `db:drop db:create db:migrate`) file `queue_schema.rb` is empty.

I have following configurations:
- `database.yml`:
```yml
development:
  primary:
    <<: *default
    database: app_development
  queue:
    <<: *default
    database: app_development_queue
    migrations_paths: db/queue_migrate
```
- `development.rb`:
```ruby
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }
```

When I run `db:drop` and then `db:prepare` it works fine.
