### ISSUE TITLE
Configuring DB issue

### ISSUE THREAD

**Issue by rctneil** [rails/solid_queue#402]
This whole multi database thing is getting super confusing.

In Development:

I totally removed Solid queue from my app and started the process to install it and configure it from scratch.

I added the gem, ran the installer. My `database.yml` looks like:

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  primary:
    <<: *default
    database: family_media_development

  queue:
    <<: *default
    database: family_media_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: family_media_test

production:
  primary:
    <<: *default
    database: family_media_production

  queue:
    <<: *default
    database: family_media_production_queue
    migrations_paths: db/queue_migrate
```

My `development.rb` and `production.rb` files both have the following in them:

```
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }
```

When I run `rails db:prepare` I get:

```
== 20240726093041 CreatePeople: migrating =====================================
-- create_table(:people)
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::DuplicateTable: ERROR:  relation "people" already exists
/workspaces/family-media/db/migrate/20240726093041_create_people.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "people" already exists (ActiveRecord::StatementInvalid)
/workspaces/family-media/db/migrate/20240726093041_create_people.rb:3:in `change'

Caused by:
PG::DuplicateTable: ERROR:  relation "people" already exists (PG::DuplicateTable)
/workspaces/family-media/db/migrate/20240726093041_create_people.rb:3:in `change'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)
```

I can see it's trying to prepare all databases in an idempotent way (as per the docs for `db:prepare` but it's failing on that one migration. There are multiple migrations above and below that `create people` one so i'm not sure why it's failing at that point?

That migration looks like:

```
class CreatePeople < ActiveRecord::Migration[7.1]
  def change
    create_table :people do |t|
      t.string :forenames
      t.string :surname
      t.string :title
      t.string :gender
      t.date :birthdate
      t.date :deathdate
      t.integer :generation
      t.integer :position
      t.integer :childof_generation
      t.integer :childof_position
      t.integer :childof_spouse_marriageno
      t.string :birthdatefeatures
      t.string :deathdatefeatures
      t.string :ancestry
      t.string :type
      t.string :marriage_person_id
      t.string :marriage_no
      t.string :marriagedate
      t.string :marriage_relation
      t.string :divorced
      t.integer :ancestry_depth, default: 0
      t.string :suffix
      t.string :nickname
      t.string :birthplace
      t.string :deathplace
      t.string :buriedplace
      t.date :burieddate
      t.string :marriedplace
      t.string :birthdateparts
      t.string :deathdateparts
      t.string :marriagedateparts
      t.string :burieddateparts
      t.string :biography
      t.boolean :highlight, default: false
      t.boolean :hidden, default: false
      t.string :fullnamedb
      t.integer :parent_id

      t.timestamps
    end
  end
end
```

If I run `rails db:schema:load:queue`, I get this error:

```
bin/rails aborted!
TypeError: Invalid type for configuration. Expected Symbol, String, or Hash. Got nil (TypeError)

        raise TypeError, "Invalid type for configuration. Expected Symbol, String, or Hash. Got #{config.inspect}"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Tasks: TOP => db:schema:load:queue => db:test:purge:queue
(See full trace by running task with --trace)
```

I've seen other people report this error but not a single answer as to what it means or how to resolve it?

I do notice however, that it did load the schema as the solid queue tables are in the queue database.

What do I do now?
