### ISSUE TITLE
Increased memory use when using `bin/jobs` to start Solid Queue?

### ISSUE THREAD

**Issue by jp524** [rails/solid_queue#405]
I'm working on a project that was using Solid Queue v0.7.0 and using `bundle exec rake solid_queue:start` to start the process. When I updated to v1.0.0 last week, I also changed the command to start Solid Queue to use `bin/jobs` per current documentation.

I noticed that the memory use of the associated Heroku app was greatly increased. I wasn't sure if this was due to updating the gem or changing the start command, so I tried changing back the command from `bin/jobs` to the Rake task and have noticed a decrease in memory use, per screenshot below.

![Screenshot 2024-11-08 at 09 11 55](https://github.com/user-attachments/assets/8a180ce6-8561-4364-8041-997f38b29c5d)

I read in the discussion on #343 that using `bin/jobs` is supposed to help with memory use thanks to eager loading, so I'm a bit puzzled by this situation.

**Comment by rosa** [comment]
Huh, that's indeed puzzling! May I ask what's your Solid Queue configuration? And whether you have [`config.rake_eager_load`](https://guides.rubyonrails.org/configuring.html#config-rake-eager-load) set to `true` by any chance?

**Comment by jp524** [comment]
Here's my Solid Queue configuration:
```yml
# config/queue.yml
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [ login, background, default ]
      threads: 3
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

staging:
 <<: *default

production:
 <<: *default

# config/recurring.yml
one:
  class: JobOne
  schedule: every 5 minutes
two:
  class: JobTwo
  schedule: every 75 minutes
solid_queue_cleanup:
  command: "SolidQueue::Job.clear_finished_in_batches"
  schedule: every day at 3 am
  queue: background
```

I don't have `config.rake_eager_load` set at all so it defaults to false I believe.
