### ISSUE TITLE
with Rails 8.1.0.alpha & friends my recurring jobs are not enqueued

### ISSUE THREAD

**Issue by wdiechmann** [rails/solid_queue#429]
I've had my fair share of issues with background/recurring jobs but this (new) issue really takes the prize - nothing gets enqueued and neither /mission_control_jobs nor Beekeeper Studio is able to shed any light on the subject 😢 

I hurried to upgrade everything to 8.1.0.alpha (solid_queue to 1.0.2) and believe to have keep the important stuff in a pristine condition, like:

- `bin/jobs` sits in my 
- `/Procfile.dev` which gets called from 
- `bin/dev` and I'd expect it to read 
- `config/recurring.yml`which looks a lot like:

```
development:
  background_job_scheduler:
    class: BackgroundManagerJob
    enabled: true
    schedule: every 60.seconds
```

and gets configured with `config/environments/development.rb` that holds - amongst other stuff 

```
  # Highlight code that enqueued background job in logs.
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue, reading: :queue } }
```

(on purpose an exact copy of production in order to verify that production does the right thing - I know that you recommend setting the adapter to :async on development)

and the `config/database.yml` has a proper filling of

```
development:
  writer:
    <<: *default
    pool: 1
    database: storage/development.sqlite3
  reader:
    <<: *default
    readonly: true
    database: storage/development.sqlite3
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate

```

and the tables are in place at `storage/development_queue.sqlite*` but, alas, empty (the \*_recurring\* ones that is)
