### ISSUE TITLE
No workers getting assigned for newly created wildcard Queues?

### ISSUE THREAD

**Issue by bmb1603** [rails/solid_queue#461]
When configuring a wildcard Queue:

```
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "queue_*"
      threads: 1
      processes: 50
```

It seems that during runtime SolidQueue won't pick up Jobs in queues that it didn't see before. If for example I add a Job to queue_12345, it only starts processing it when SolidQueue is restarted.

Is this behavior intentional? Would there be a way to reload the configuration without restarting SolidQueue?
