### ISSUE TITLE
Upgrading to 1.1.1 makes recurring job to fail

### ISSUE THREAD

**Issue by max-chem-eng** [rails/solid_queue#468]
Ruby: 3.4.1
Rails: 8.0.1
`solid_queue` running as a plug_in
This simple recurring job fails:
```yaml
production:
  periodic_cleanup:
    class: CloseTripsJob
    queue: background
    schedule: every hour
```

with this error:
```console
10:48:03 web.1  | Invalid recurring tasks:
10:48:03 web.1  | - production: Schedule is not a supported recurring schedule, either command or class_name must be present
10:48:03 web.1  | Exiting...
10:48:07 web.1  | Detected Solid Queue has gone away, stopping Puma...
```

**EDIT: it only fails if the only environment declared is production and trying to run the app in development**

**Comment by rosa** [comment]
🤔  it seems that `CloseTripsJob` might not be defined? Does that exist?

**Comment by jnstq** [comment]
Same for me, I had remove the environment in order to boot solid queue.

See if this works:

```yaml
periodic_cleanup:
  class: CloseTripsJob
  queue: background
  schedule: every hour
```

**Comment by max-chem-eng** [comment]
> 🤔 it seems that `CloseTripsJob` might not be defined? Does that exist?

it started failing when upgraded to `1.1.1`, `1.1.0` works fine

**Comment by RemoteCTO** [comment]
Same issue for me. 
On examining Mission Control, my list of workers was empty. Reverting to `1.1.0` and things are back to normal.

**Comment by rosa** [comment]
To be clear, with 1.1.0, invalid recurring tasks would be silently ignored, leading to confusing situations where people didn't know why they weren't being run. With 1.1.1, these fail. If reverting to 1.1.0 works, fine, it might simply mean that they're ignored.

**Comment by rosa** [comment]
@jnstq nothing has changed regarding the environment keys in `recurring.yml`. If you remove it and that works, it might be that the recurring tasks aren't being loaded at all.

**Comment by rosa** [comment]
Oh, @max-chem-eng, I just realised that the recurring task failing for you is `production` 😕 That's very odd. Is this failing in `development` only?

**Comment by max-chem-eng** [comment]
> To be clear, with 1.1.0, invalid recurring tasks would be silently ignored, leading to confusing situations where people didn't know why they weren't being run. With 1.1.1, these fail. If reverting to 1.1.0 works, fine, it might simply mean that they're ignored.

thanks for your input
with version 1.1.0 I can confirm that the recurring task is working just fine, if I update it to:
```yaml
development:
  periodic_cleanup:
    class: CloseTripsJob
    queue: background
    schedule: every second
```
I see it running without issues

If I update it to `1.1.1` it fails with the mentioned error:
```console
Invalid recurring tasks:
- production: Schedule is not a supported recurring schedule, either command or class_name must be present
```
regardless I run it as plug in or in its own terminal
