### ISSUE TITLE
Jobs not being worked on

### ISSUE THREAD

**Issue by thisIsLoading** [rails/solid_queue#476]
i have (i believe after one of the latest updates, but cant tell) blocked jobs like this

![image](https://github.com/user-attachments/assets/87a7efc5-d258-4466-a5dc-f2fb88298cc1)

they are being scheduled like this:

```
production:
  predicted_funding_data:
    command: Funding::FundingRate.new.sync_all_predicted_funding_rates
    schedule: '* * * * *'
```

which basically just schedules a bunch of jobs of these:

```
class Funding::SyncPredictedFundingRatesJob < ApplicationJob
  limits_concurrency to:       10,
                     duration: 1.second,
                     key:      ->(exchange_name, perp_pair) { "Exchange_#{exchange_name}_PredictedFundingRate" }

  def perform(exchange_name, perp_pair)
    exchange = Exchange.find_by(name: exchange_name)

    # Initialize the appropriate service
    funding_rates_service = Funding::FundingRate.new(exchange.name)

    # Synchronize funding rates
    funding_rates_service.sync_predicted_funding_rate(exchange, perp_pair)
  end
end
```

the thing is, the first couple hundred jobs are being executed just fine but after a while it just stops and my workers are idleing:

![image](https://github.com/user-attachments/assets/730ebba5-2880-4c7e-87d7-310f0e8c85f4)

until the next run which makes the workers wake up and process a couple hundred jobs (not all) and then go back idle again, after a couple hundred.

this was working just fine until like 2 or so weeks ago.

i am using solid queue v1.1.2

is there anything i do wrong?

**Comment by rosa** [comment]
What are you setting for `concurrency_maintenance_interval` in your dispachers configuration?

**Comment by thisIsLoading** [comment]
hi @rosa , thank you for coming back to me that quick!

i dont have that set, this is my queue.yml

```
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 5
      processes: 5
      polling_interval: 0.1

development:
  <<: *default
  workers:
    - queues: "*"
      threads: 5
      processes: 5 # Set to 5 processes in development
      polling_interval: 0.1

test:
  <<: *default

production:
  <<: *default
```
