### ISSUE TITLE
development env, high CPU usage

### ISSUE THREAD

**Issue by alex29ua** [rails/solid_queue#482]
Trying a default install of solid_queue 1.1.2, with a still empty queue DB. 
Ruby 3.1.6, Rails 7.1.5.1, Ubuntu 22.04

When I run `rails solid_queue:start`, CPU usage goes crazy. It looks like this:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   2859 user    20   0 1032208 183844  17444 R  93.7   1.1   0:22.42 solid-queue-supervisor(1.1.2): supervising 2875, 2878
   2875 user    20   0  966868 179332   8632 R  79.7   1.1   0:17.48 solid-queue-dispatcher(1.1.2): dispatching every 1 seconds
   2878 user    20   0  900884 179320   8360 R  74.7   1.1   0:16.36 solid-queue-worker(1.1.2): waiting for jobs in *
```

and it never goes down. I tried changing the polling to 500/50 or even slower, but it doesn't change anything at all in usage. 

Is it some misconfiguration issue?

Nothing suspicious in the logs as I can see.

**Comment by rosa** [comment]
I don't see anything like this in my machine 😕  Could yo provide more details? For example, Solid Queue version, OS..?

**Comment by alex29ua** [comment]
SQ 1.1.2. Tried with ruby 3.1.6 and 3.0.6 (similar to my production versions for now).

OS is Ubuntu 22.04 (technically, it's WSL in Windows 11). Ruby, Rails, Mysql see in my first message

I tried setting up a new Rails app from scratch, then simple SQ config according to installation guide, but I got the same results. Looks like mysql experiences some load too, so probably SQ makes a lot of requests? I cannot see anything in `show processlist` in mysql console though. And the queue db is really empty, a few rows about the workers started, that's it.

**Comment by alex29ua** [comment]
tried with this queue.yml config
```
default: &default
  dispatchers:
    - polling_interval: 30
      batch_size: 500
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 10
```
to make it really slooow - but I still get the same huge load.

**Comment by rosa** [comment]
Could you try with Solid Queue <= v1.0.2? Just to rule out some changes around worker/dispatcher polling and the interruptible sleep?

**Comment by hms** [comment]
@rosa 

"wasn't me".... 😏 (at least I really hope so 🤞 )

All kidding aside, I did spin up my dev env to reconfirm that see almost zero CPU resources when SQ is quiescent.  For comparisons and to keep the information flowing: M3 Mac, OSX 15.2, Postgres@17(primary, I test across all 3 databases at the latest release), ruby 3.4, Rails 7.2.2.

Before pushing up my PRs, I did test across Ruby 3.1 - 3.6 and on Rails 7.1.

**Comment by alex29ua** [comment]
@rosa nicely spotted!
`1.0.2` works perfectly, I can barely find it in the processes. 
`1.1.0` and up - goes full on with CPU again. 

I only have mysql5.7 to test with, though I set the recommended `use_skip_locked = false` in all the cases.

**Comment by alex29ua** [comment]
A little bit more info on SQ 1.1.2 tests:
Ruby 3.1.6 is full CPU usage
Ruby 3.2.6 is totally ok. 

I'm currently upgrading my app to 3.2.6 so it might be not that important for me any longer, but still probably worth noticing.

**Comment by rosa** [comment]
Huh, interesting! I wonder if it's something specific to
> Ubuntu 22.04 (technically, it's WSL in Windows 11).

since @hms couldn't reproduce this in Ruby 3.1.2 🤔

**Comment by markivancho** [comment]
I can confirm the same problem with high CPU usage and many queries to DB.
The graph from Datadog shows hits in solid_queue 1.1.2 and a low amount of hits after rollback to 1.0.2.

queue_dispatcher.yml
```
default: &default
  dispatchers:
    - polling_interval: 5
      batch_size: 500

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

```

queue_default.yml
```
default: &default
  workers:
    - queues: [default, medium]
      threads: 10
      processes: 1
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

queue_heavy.yml
```
default: &default
  workers:
    - queues: [heavy, super_heavy]
      threads: 5
      processes: 1
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

```

![Image](https://github.com/user-attachments/assets/1b2e462f-3980-4687-9246-9137e28539cf)
