### ISSUE TITLE
Better scheduler configuration

### ISSUE THREAD

**Issue by ThomasCrambert** [rails/solid_queue#484]
Hello 👋,

Currently, there’s no configuration option to specify if a scheduler should be started or not, this is decided if a recurring task file is given or not.

In our case, we would like to have only one scheduler for better isolation. To do that, we have to use the following configuration:
```
production:
  workers:
    - processes: 0
      threads: 0
```

This will explicitly tell solid_queue to not boot anything apart from the supervisor and since we also give it a recurring task file, it will also start a scheduler.

This workaround works fine for us but I feel like there could be something more intuitive. If you think the same, I can try to come up with a solution. 👍

**Comment by rosa** [comment]
Hey @ThomasCrambert, this is almost wired up but not exactly what you want, via [these not yet documented options](https://github.com/rails/solid_queue/blob/ef7b4d0cf8c8cab61a59692cece8e390d3e2bedc/lib/solid_queue/configuration.rb#L89-L91). 

If you don't specify any workers, it also works, you don't need to set `processes` and `threads` to `0`:

In our case, we run the dispatchers and scheduler separately from workers with this configuration: 
```
# config/solid_queue/dispatching.yml

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
    - polling_interval: 2
      batch_size: 500
```

We have `recurring.yml` in the default place. Then we just run this: 
```
bin/jobs -c config/solid_queue/dispatching.yml
```

And that starts the 2 dispatchers and 1 scheduler. If you want only 1 scheduler, then perhaps we need an `only_recurring` option (besides the empty configuration workaround).
