### ISSUE TITLE
No worker registered and no job processed by Solid Queue in staging environment when using the Puma plugin

### ISSUE THREAD

**Issue by Florent2** [rails/solid_queue#487]
I use Solid Queue 1.1.2, Rails 7.2.1 and Puma 6.4.2.

I have `plugin :solid_queue` in my `puma.rb` file.

My `config/queue.yml` file is:

```yaml
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
```

Locally with the development environment and the staging environment, the Puma plugin registers a worker on server boot and can process jobs.

But on my staging server no worker is registered (Mission Control lists none, and no records are created in the `solid_queue_processes` table). I don't see any errors related to Solid Queue in the logs.

On my staging server if I run `RAILS_ENV=staging bin/jobs` a worker is registered and jobs are processed.

Is there any setting or configuration that would explain that Solid Job does not work on a staging server when using the Puma plugin?
