### ISSUE TITLE
Segmentation fault in pg Gem during solid_queue execution (connect_poll method)

### ISSUE THREAD

**Issue by hatsu38** [rails/solid_queue#494]
This is one of my favorite gems. Thank you for your continued maintenance!

## Environment

```
❯ uname -a
Darwin Mac-S20240206 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

❯ psql --version
psql (PostgreSQL) 14.15 (Homebrew)

❯ bin/rails -v
Rails 7.2.2.1

❯ bundle show solid_queue
/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/solid_queue-1.1.2

❯ bundle show pg
/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/pg-1.5.9
```

## Description
When running solid_queue with bin/jobs, a segmentation fault (SIGBUS) occurs in the pg Gem during the connect_poll method.

<details><summary>bin/jobs log</summary>

```
-- Threading information ---------------------------------------------------
Total ractor count: 1
Ruby thread count for this ractor: 2

-- Machine register context ------------------------------------------------
  x0: 0x00000001ff68cb40  x1: 0x0000600002665d00  x2: 0x0000000000000000
  x3: 0x00000001ff68cb40  x4: 0x0000000197695e70  x5: 0x00000001ff68c1d0
  x6: 0x0000000000000002  x7: 0x00000001977f2850 x18: 0x0000000000000000
 x19: 0x000000016f8a38d8 x20: 0x0000600002665d00 x21: 0x000000003b9aca00
 x22: 0x000000016f8a3cb8 x23: 0x00000001507eba30 x24: 0x0000000150663db8
 x25: 0xaaaaaaaaaaaaaaaa x26: 0x0000000150663ea0 x27: 0x000000016f8a3e58
 x28: 0x0000000000000001  lr: 0xeb2e80019a887e30  fp: 0x000000016f8a3810
  sp: 0x000000016f8a3810

-- C level backtrace information -------------------------------------------
BUS received in SEGV handler
/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/pg-1.5.9/lib/pg/connection.rb:703: [BUG] Segmentation fault at 0x0000000000000110
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin23]

-- Crash Report log information --------------------------------------------
   See Crash Report log file in one of the following locations:             
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0132 p:---- s:0770 e:000769 CFUNC  :connect_poll
c:0131 p:0351 s:0766 e:000765 METHOD .rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/pg-1.5.9/lib/pg/connection.rb:703
c:0130 p:0141 s:0753 e:000752 METHOD /.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/pg-1.5.9/lib/pg/connection.rb:844
c:0129 p:0007 s:0744 e:000743 METHOD /.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/pg-1.5.9/lib/pg/connection.rb:772
c:0128 p:0012 s:0738 e:000737 METHOD /.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/pg-1.5.9/lib/pg.rb:63
c:0127 p:0006 s:0732 e:000731 METHOD /.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters

...
```

</details>

### Additional Information
The crash report file from macOS is available in ~/Library/Logs/DiagnosticReports. Please let me know if it is required for further debugging.

## Setting

config/queue.yml
```yml
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
```

config/database.yml

```
default: &default
  adapter: postgresql
  encoding: unicode
  charset: utf8
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 3 ) %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'insight_sky_backend_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'insight_sky_backend_test') %><%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
```

config.puma.rb
```rb
threads_count = ENV.fetch("RAILS_MAX_THREADS", 3)
threads threads_count, threads_count

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
port ENV.fetch("PORT", 3000)

# Allow puma to be restarted by `bin/rails restart` command.
plugin :tmp_restart
# plugin :solid_queue

# Specify the PID file. Defaults to tmp/pids/server.pid in development.
# In other environments, only set the PID file if requested.
pidfile ENV["PIDFILE"] if ENV["PIDFILE"]
```
