### ISSUE TITLE
Question regarding single database configuration

### ISSUE THREAD

**Issue by rnestler** [rails/solid_queue#507]
For a small app running on Heroku I want to use solid_queue (solid_cable and solid_cache as well) with just a single postgres database.

The guide [here](https://github.com/rails/solid_queue/blob/9cd6bc3a16826d04c63ba667c93bd8cbb094db81/README.md#single-database-configuration) reccommends to

> Running Solid Queue in a separate database is recommended, but it's also possible to use one single database for both the app and the queue. Just follow these steps:
>
>    1. Copy the contents of db/queue_schema.rb into a normal migration and delete db/queue_schema.rb
>    2. Remove config.solid_queue.connects_to from production.rb
>    3. Migrate your database. You are ready to run bin/jobs
>
>You won't have multiple databases, so database.yml doesn't need to have primary and queue database.

In other resources (https://briancasel.gitbook.io/cheatsheet/rails-1/setup-solid-queue-cable-cache-in-rails-8-to-share-a-single-database) it is recommended to configure 4 different databases to actually use the same database:
```yaml
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
```
But this leads to very strange behavior, such as `rails db:migrate` creating three identical schemas: `db/cable_schema.rb  db/cache_schema.rb  db/queue_schema.rb  db/schema.rb`.

So my questions is: When going with the instructions form this repository shouldn't I still have a `connects_to` call in `production.rb` to ensure that solid_queue uses it's own connection pool? So replacing
```ruby
config.solid_queue.connects_to = { database: { writing: :queue } }
```

with

```ruby
config.solid_queue.connects_to = { database: { writing: :primary } }
```
