### ISSUE TITLE
How do I maintain the order and force sequential processing?

### ISSUE THREAD

**Issue by chriso0710** [rails/solid_queue#532]
Hi all, 

I am trying to achive running some jobs in a special queue with the following configuration: 
- in the order that they are enqueued and 
- sequentially (not parallel)

```
- queues: "sequential"
  threads: 1
  processes: 1
  polling_interval: 0.1
```

Is that even possible?
I tried the ```limits_concurrency``` setting, but it does not seem to work for me and my jobs are still being processed in parallel.
What am I missing here?

Thank you
Christian

**Comment by rosa** [comment]
Hey @chriso0710, with that configuration, your jobs should definitely be processed one by one. Do you have just that one worker configured? Or do you have more?

**Comment by chriso0710** [comment]
This is my workers config:
```
workers:
    - queues: "default"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: "corrector"
      threads: 1
      processes: 1
      polling_interval: 0.1
```

And in my job I have:
```
class SaveTranscriptJob < ApplicationJob
  queue_as :corrector

  def perform(content, user_id)
    ...
  end
end
```
