### ISSUE TITLE
Everytime I run db:migrate, db/queue_schema.rb is emptied, and tables don't exist (rails 8.0.3)

### ISSUE THREAD

**Issue by rathboma** [rails/solid_queue#540]
Hey team,

I started using solid_queue in development, but I'm continually running into a problem moving between computers.

Whenever I move from my laptop to my desktop and run `db:migrate`, I seem to be missing one solid_queue table or another, and the db/queue_schema.rb is emptied.

Example error from this morning:

```
/home/rathboma/.rvm/gems/ruby-3.2.3/gems/activerecord-8.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec': ERROR:  relation "solid_queue_recurring_tasks" does not exist (PG::UndefinedTable)
LINE 10:  WHERE a.attrelid = '"solid_queue_recurring_tasks"'::regclas...

```

I've seen many issues that supposedly deal with this, but none of them seem to work for me. I really don't know why it is behaving this way -- I would expect it to have migration files, but it doesn't seem to?

**Comment by rosa** [comment]
Hey @rathboma, you don't have to run `db:migrate`. You just need to run `db:prepare`, as the instructions explain.

**Comment by rosa** [comment]
Hmm... that's weird! Have you followed [the instructions to set up solid queue in development](https://github.com/rails/solid_queue?tab=readme-ov-file#usage-in-development-and-other-non-production-environments)? 🤔

**Comment by rathboma** [comment]
Yes! 

I had it enabled for production, then updated my code to add it in for development last week, now I can get it working by wiping my database, restoring the queue_schema file, then running prepare, but otherwise it refuses to set it up right.

My code looks like this:

```yaml

development:
  primary:
    adapter: postgresql
    database: fuego_development
    pool: 5
    timeout: 5000
    host: localhost
    username: postgres
    port: 5556
    password: example
  queue:
    adapter: postgresql
    database: fuego_development_queue
    migrations_paths: db/queue_migrate
    pool: 5
    timeout: 5000
    host: localhost
    username: postgres
    port: 5556
    password: example
```

```ruby
# development.rb
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }
  config.solid_queue.logger = ActiveSupport::Logger.new(STDOUT)
```

There's nothing in the queue database:

![Image](https://github.com/user-attachments/assets/9515c62a-52cd-4a76-a450-b52fc5a593fa)
