### ISSUE TITLE
Can't set single thread/process

### ISSUE THREAD

**Issue by barnaclebarnes** [rails/solid_queue#541]
I have the following setup:

```
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 0.1
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

But that worker is always running three concurrent jobs:

<img width="1390" alt="Image" src="https://github.com/user-attachments/assets/9a5cb374-d4f3-4f7c-aeb9-4bbdb38b494e" />

Its configuration shows:

```
{
  "polling_interval": 0.1,
  "queues": "*",
  "thread_pool_size": 3
}
```

I can't for the life of me work out how to set this to process a single job at a time. The reason I need to do this is that I'm using a GPU to analyse images using AI and it can only really handle a single image at a time before it blows up with memory constraints.

Any ideas of what I am doing wrong here? I even tried to add `thread_pool_size: 3` rot the config but no luck. I'm using the latest version of `solid_queue`
