### ISSUE TITLE
Specify logger for recurring task

### ISSUE THREAD

**Issue by Benoit-Baumann** [rails/solid_queue#551]
Hi @rosa,

Thanks for the awesome work ! 

We are currently using the [whenever gem](https://github.com/javan/whenever) to manage recurring rake tasks and are considering using SolidQueue's recurring tasks to replace this gem. One thing we love about `whenever` is the ability to specify a logger per cron job (cf https://github.com/javan/whenever/wiki/Output-redirection-aka-logging-your-cron-jobs).

It would be nice to have something similar in SolidQueue, for example : 

```yml
production:
  a_periodic_job:
    class: MyJob
    args: [ 42, { status: "custom_status" } ]
    schedule: every second
    logger:  "log/a_periodic_job.log"
  a_cleanup_task:
    command: "DeletedStuff.clear_all"
    schedule: every day at 9am
    logger:  "log/a_cleanup_task.log"
  another_task:
    command: "DoStuff.perform"
    schedule: every day at 9am
```

If no logger is specify, SolidQueue's default logger is used.

What do you think about it ?
