### ISSUE TITLE
Is it a bad idea to run multiple dispatchers?

### ISSUE THREAD

**Issue by kyrofa** [rails/solid_queue#573]
I've been running Solid Queue for a while now, with good success, but I had a bad experience today that has me re-thinking my configuration. I have a single Solid Queue instance running with the following configuration:

```yaml
dispatchers:
  - polling_interval: 1
    batch_size: 500
workers:
  - queues: "*"
    threads: 3
    polling_interval: 0.1
```

Today I had the node running that instance turn into a zombie. It took me a while to convince AWS to kill it and give me another one, all while my job queue built up and my alarms went off. I prevent this kind of thing from causing downtime with our Rails instances by running multiple, on different nodes. Can I do the same thing with Solid Queue? I know I can run multiple workers, my concern is more about the dispatchers: will multiple entities putting things into the `solid_queue_ready_executions` table be okay?
