### ISSUE TITLE
How to setup testing environment in solit queue

### ISSUE THREAD

**Issue by khoanguyenpionero** [rails/solid_queue#588]
I write unit test end meet error
Failure/Error: MailJob.set(wait_until: reserved_at).perform_later(self.id)
     
     SolidQueue::Job::EnqueueError:
       ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "solid_queue_jobs" does not exist
       LINE 10:  WHERE a.attrelid = '"solid_queue_jobs"'::regclass
                                    ^
I use second database for solid queue but in testing. It call to primary database to get solid_Queue. How can I fix this issue.
`database.yml
```
`test:
  primary:
    <<: *default
    database: test
    username: root
    password: 

  queue:
    <<: *default
    database: test_queue
    username: root
    password: 
    migrations_paths: db/queue_migrate
```
